services:
  mebender:
    container_name: mebender
    image: mebender
    restart: unless-stopped
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./resources/:/root/resources/ 

    
    