services:
  mebender:
    container_name: mebender
    image: mebender
    restart: unless-stopped
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
      - PORT=${PORT}
      - MOUNT_HOST_DIR=${MOUNT_HOST_DIR}
      - MOUNT_TARGET_DIR=${MOUNT_TARGET_DIR}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${MOUNT_HOST_DIR}:${MOUNT_TARGET_DIR}

    
    